version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    environment:
      FLASK_APP: app.py  # Replace with your actual app file
      REDIS_URL: redis://redis:6379/0  # Use the service name "redis" for the hostname

  redis:
    image: "redis:latest"
    ports:
      - '6379:6379'
