name: "Installing Python Dependencies"
description: "It will install python library"
runs:
  using: "composite"
  steps:
    run: |
      python -m pip install --upgrade pip
      pip install Flask matplotlib numpy pytest
